# Generated by Django 5.2.12 on 2026-03-28 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='external_order_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='special_request',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='notes',
        ),
    ]
