# Generated by Django 5.2.12 on 2026-03-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_external_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='external_order_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='special_request',
            field=models.TextField(blank=True, null=True),
        ),
    ]
