# Generated by Django 5.2.12 on 2026-03-28 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='cost_price',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='prep_time_mins',
        ),
    ]
