# Generated by Django 5.2.12 on 2026-03-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_remove_category_description_remove_category_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='prep_time_mins',
            field=models.IntegerField(default=15),
        ),
    ]
