# Generated by Django 5.2.12 on 2026-03-28 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='discount_reason',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='commission_amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='commission_pct',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='net_settlement',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='razorpay_signature',
        ),
    ]
