# Generated by Django 5.2.12 on 2026-03-28 18:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('legal_name', models.CharField(blank=True, max_length=300)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('website_url', models.URLField(blank=True)),
                ('address', models.TextField()),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('favicon_url', models.URLField(blank=True, null=True)),
                ('timezone', models.CharField(default='Asia/Kolkata', help_text='IANA timezone for receipts and reporting.', max_length=64)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('extra_settings', models.JSONField(blank=True, default=dict, help_text='Non-secret frontend data: theme, hours, copy. Do not put API keys here.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'restaurant config',
                'verbose_name_plural': 'restaurant config',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('table_number', models.CharField(max_length=10, unique=True)),
                ('seating_capacity', models.PositiveIntegerField()),
                ('section', models.CharField(default='general', help_text='Section label for your floor plan (indoor, patio, VIP, …).', max_length=64)),
                ('status', models.CharField(choices=[('empty', 'Empty'), ('occupied', 'Occupied'), ('bill_requested', 'Bill requested'), ('cleaning', 'Cleaning')], default='empty', max_length=20)),
                ('qr_token', models.CharField(max_length=64, unique=True)),
                ('qr_token_expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['table_number'],
            },
        ),
    ]
