# Generated by Django 5.2.12 on 2026-03-28 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantconfig',
            name='extra_settings',
        ),
        migrations.RemoveField(
            model_name='restaurantconfig',
            name='favicon_url',
        ),
        migrations.RemoveField(
            model_name='restaurantconfig',
            name='logo_url',
        ),
        migrations.RemoveField(
            model_name='restaurantconfig',
            name='website_url',
        ),
    ]
