# Generated by Django 5.2.12 on 2026-03-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0002_remove_restaurantconfig_extra_settings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='section',
            field=models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor'), ('vip', 'VIP'), ('bar', 'Bar')], default='indoor', max_length=20),
        ),
        migrations.AlterField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('empty', 'Empty'), ('occupied', 'Occupied'), ('bill_requested', 'Bill Requested'), ('cleaning', 'Cleaning'), ('reserved', 'Reserved')], default='empty', max_length=20),
        ),
    ]
