# Generated by Django 5.2.12 on 2026-03-28 18:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True)),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_orders', models.IntegerField()),
                ('dine_in_revenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('swiggy_revenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('zomato_revenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('avg_order_value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('avg_table_duration_mins', models.IntegerField()),
                ('payment_method_breakdown', models.JSONField()),
                ('channel_metrics', models.JSONField(blank=True, help_text='Optional extra channel keys (website, takeaway, …) without schema changes.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'daily analytics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ItemAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('quantity_sold', models.IntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('margin_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analytics_rows', to='menu.menuitem')),
            ],
            options={
                'ordering': ['-date', 'menu_item_id'],
                'constraints': [models.UniqueConstraint(fields=('menu_item', 'date'), name='analytics_itemanalytics_menu_item_date_uniq')],
            },
        ),
    ]
