# Generated by Django 5.2.12 on 2026-03-28 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyanalytics',
            name='channel_metrics',
        ),
        migrations.RemoveField(
            model_name='itemanalytics',
            name='margin_amount',
        ),
    ]
