# Generated by Django 5.2.12 on 2026-03-28 18:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venue', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TableSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qr_token_used', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('open', 'Open'), ('bill_requested', 'Bill requested'), ('paid', 'Paid'), ('closed', 'Closed'), ('abandoned', 'Abandoned')], default='open', max_length=20)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('bill_requested_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('captain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table_sessions_attended', to=settings.AUTH_USER_MODEL)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='venue.table')),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
    ]
