# Generated by Django 5.2.12 on 2026-03-28 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table_sessions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablesession',
            name='notes',
        ),
    ]
