# Generated by Django 5.2.12 on 2026-03-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_sessions', '0002_remove_tablesession_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablesession',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
